[project]
name = "sapheneia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.7.0",
    "jaxlib>=0.7.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.5",
    "seaborn>=0.13.2",
    "timesfm>=1.3.0",
]
